---
name: Michael J. Carter
address: "McMaster University \\tabularnewline
  Ivor Wynne Centre Room 203 \\tabularnewline
  Hamilton ON, Canada L8S 4K1"
www: cartermaclab.org
phone: +1 905 525 9140 x20391
email: "cartem11@mcmaster.ca"
# twitter: carterjmike
github: carterjmike
linkedin: carterjmike
orcid: 0000-0002-0675-4271
classoption: letterpaper
date: "`r format(Sys.Date(), '%B %Y')`"
date-format: "MMMM YYYY"
position: "Assistant Professor \\tabularnewline Department of Kinesiology"
number-sections: true
number-depth: 2
fontsize: "12pt"
format: 
  cv-pdf:
    include-in-header:
      - text: |
          \definecolor{headcolor}{HTML}{011640}
          \usepackage[sfdefault]{atkinson}
          \usepackage[T1]{fontenc}
          \usepackage{colortbl}
          \arrayrulecolor{white}
          \usepackage{etaremune}
          \usepackage{csquotes}
          \MakeOuterQuote{"}
          \usepackage[none]{hyphenat}
# nord headcolor options: dark blue 5e81ac
# kanagawa headcolor options: dark blue 011640 lightblue 2d5873
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  cache = FALSE
)
library(kableExtra)
library(tidyverse)
# library(RefManageR)
# source("R/add_bib_section.R")
source("pretty.R")
```

\renewcommand{\labelitemi}{\textbullet}
\renewcommand{\labelitemii}{\textbullet}


# 1. Name in full

Michael James Joseph Carter


# 2. Business address

{{< include sections/_business-address.qmd >}}


# 3. Educational background

{{< include sections/_education.qmd >}}


# 4. Current status at McMaster


# 5. Professional organizations

{{< include sections/_professional-organizations.qmd >}}


# 6. Employment history

## a) Academic

{{< include sections/_employment.qmd >}}

## b) Consultation

None.

## c) Other

{{< include sections/_visitorships.qmd >}}


# 7. Scholarly and professional activities

{{< include sections/_activities.qmd >}}


# 8. Areas of interest (research, teaching, consulting)

## a) Research

{{< include sections/_research-interests.qmd >}}

## b) Teaching

TODO

## c) Consulting

TODO


# 9. Honours and awards

{{< include sections/_honours.qmd >}}


# 10. Courses taught (last 5 years)

TODO


# 11. Contributions to teaching pratice

## a) Pedagogic innovation and/or development of technology-enhanced learning

## b) Leadership in delivery of educational programs

## c) Course/curriculum development

## d) Development/evaluation of educational materials and programs

## e) Other



# 12. Supervisorships

## a) Masters

## b) Doctoral

## c) Postdoctoral

## d) Clinical/professional

## e) Supervisory committees

## f) Other


# 13. Lifetime research funding

## a) Current

## b) Previous


# 14. Lifetime Publications


# 15. Presentations at Meetings

## a) Invited


## b) Contributed


# 16. Patents, inventions, and copyrights


# 17. Administrative responsibilities


# 18. Other responsibilities




# Career interruptions, delays, and/or professional breaks

{{< include sections/_interruptions.qmd >}}






